# Setup LAMP Stack
- hosts: 144.217.243.29
  tasks:
    - name: Install yum utils
  package:
    name:
    - yum-utils
    - "@Development tools"
    lock_timeout: 180
    - name: install lamp stack
      become: yes
      become_user: root
      yum:
        pkg:
          - httpd
          - mysql-server
          - php
          - php-mysql
        state: present
        update_cache: yes

    - name: start httpd service
      become: yes
      become_user: root
      service:
        name: httpd
        state: started
        enabled: yes

    - name: start mysql service
      become: yes
      become_user: root
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create target directory
      file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      become: yes
      become_user: root
      command: echo "welcome" >> /var/www/html/index.php
