- hosts: 51.158.162.66
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
      
    - name: 2. install PHP module for Apache
      apt: name=libapache2-mod-php5 state=present

    - name: 3. start Apache
      service: name=apache2 state=running enabled=yes

    - name: 4. install Hello World PHP script
      copy: src=index.php dest=/var/www/index.php mode=0664
